language: php

# faster builds on docker-container setup
sudo: false

# used for HHVM
addons:
  apt:
    packages:
      - tidy

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
    fast_finish: true
    exclude:
        - php: hhvm
          env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
    allow_failures:
        - php: hhvm

branches:
    only:
        - v2

before_script:
    - composer self-update
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    # disable xdebug since we don't use code-coverage for now
    - if [[ $TRAVIS_PHP_VERSION != '5.6' && $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then phpenv config-rm xdebug.ini; fi
    - if [[ "$DB" = "pgsql" ]]; then psql -c 'create database wallabag;' -U postgres; fi;

script:
    - ant prepare-$DB
    - bin/phpunit -v
